# Site Settings
baseurl: ""
url : "https://nowonder.me"

collections:
  references:
    output: true

plugins: 
  - jekyll-paginate
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag
  - jekyll-redirect-from

permalink: /:categories/:title/

tracks:
  google_analytics: UA-98817606-5
  baidu_tongji: 649831849b6b50d723160029db5b5e7c

defaults:
  - scope:
      path: ""
      type: "references"
    values:
      layout: "ref"

# Blog Settings
theme_settings :
  title : NWM历险记
  favicon : assets/favicon.ico

  # Profile Settings
  profile :
    image : assets/img/site-logo.png
    description: 我的生活平淡无奇，没有历险记
      
  # Disqus
  disqus_shortname :

# Pagination
paginate: 5
paginate_path: "blog/page:num"

# Build Ssttings
sass:
  sass_dir: _sass
  style: :compressed
bootstrap:
  assets: true
