# Site Settings
baseurl: ""
url : "https://naye0ng.github.io"

collections:
  references:
    output: true

plugins: 
  - jekyll-paginate
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag   

permalink: /blog/:title/

defaults:
  - scope:
      path: ""
      type: "references"
    values:
      layout: "ref"

# Blog Settings
theme_settings :
  title : Nowonder.me
  favicon : assets/favicon.ico

  # Profile Settings
  profile :
    image : assets/img/site-logo.png
    username : No Wonder Me
    description : 我的生活平淡无奇，没有历险记
    experience :
      - start : 2017-05-03
        end : 2018-05-06
        experience : company name, title
    skills : 
      - skill : HTML5 & CSS
        value : 85  # Percent value
      
  # Disqus
  disqus_shortname :

# Pagination
paginate: 5
paginate_path: "blog/page:num"

# Build Ssttings
sass:
  sass_dir: _sass
  style: :compressed
bootstrap:
  assets: true
